### ISSUE TITLE
Games Page

### ISSUE THREAD

**Issue by komarnickolas** [Jypotheren734x/Micro-Blog#7]

**Comment by a-littlefield** [comment]
I was thinking, unless you are pretty set on the API, we could just add somewhere around 20 games to the game page and just have the user add to their favorites through that, what do you think?

**Comment by komarnickolas** [comment]
That sounds good, we'll have to modify the database for that. We would need to remove favorite_games from user and create a game and user_game table.

**Comment by a-littlefield** [comment]
I think we have a Game table so we should just have to add the user_game table, did you create the database already? I don't see it...

**Comment by komarnickolas** [comment]
Ruby mine automatically ignores the db folder, just make the migrations yourself

**Comment by komarnickolas** [comment]
We don't have a game table at the moment, I have figured out how to make the site fully live. I can just launch it and you can access the db on my computer

**Comment by a-littlefield** [comment]
Alright works for me!

**Comment by komarnickolas** [comment]
Make the site live? or the migrations yourself?

**Comment by a-littlefield** [comment]
You can make the site live and we can just do db stuff tomorrow.

**Comment by komarnickolas** [comment]
k, give me a second and I'll have the ip

**Comment by komarnickolas** [comment]
k, try this: http://67.2.95.184:4567

**Comment by a-littlefield** [comment]
Didnt connect...

**Comment by komarnickolas** [comment]
k, I think it has to do with my router give me a minute to configure the firewall

**Comment by komarnickolas** [comment]
try this: https://jypotheren.herokuapp.com/

**Comment by a-littlefield** [comment]
That one works

**Comment by komarnickolas** [comment]
I updated a lot into the master branch just now, If you can pull it and merge it into all of the branches you are working on now that would be great

**Comment by a-littlefield** [comment]
On it, give me a sec it removed all the changes I made to trending and popular Im going to try and get them back

**Comment by komarnickolas** [comment]
What files where the changes to?

**Comment by a-littlefield** [comment]
popular.erb, trending.erb, main.css and index.css all lost changes, but it wasnt much so honestly not a huge deal. Ill just add the template of what I had before and push up the branch.

**Comment by komarnickolas** [comment]
K, can you still launch it locally?

**Comment by a-littlefield** [comment]
Yup

**Comment by komarnickolas** [comment]
Awesome, keep doing it locally so your can view your changes, but the database should be using the cloud one

**Comment by komarnickolas** [comment]
If you could create an account on the site, I can check the db to make sure that is working

**Comment by a-littlefield** [comment]
Yeah ill do that

**Comment by a-littlefield** [comment]
I think it worked but im not sure, its still asking me to login haha

**Comment by komarnickolas** [comment]
I can see it in the databse, so you should be good. That worked from your local launch, right?

**Comment by a-littlefield** [comment]
I cant launch hello.rb through ruby for some reason, not sure what the error is telling me either so i cant locally launch from the master branch...

**Comment by komarnickolas** [comment]
okay, so you made a user with the live site then? I have the same problem, it's a rake issue, it doen't like the tasks existing

**Comment by a-littlefield** [comment]
found character that cannot start any token while scanning for the next token at line 2 column 1 (Psych::SyntaxError) is the error Im receiving

**Comment by komarnickolas** [comment]
Same error for me

**Comment by a-littlefield** [comment]
Ya I did.. weird...

**Comment by komarnickolas** [comment]
What happen when you run bundler?

**Comment by a-littlefield** [comment]
An error occurred while installing pg (0.21.0), and Bundler cannot
continue.
Make sure that `gem install pg -v '0.21.0'` succeeds before bundling.

**Comment by komarnickolas** [comment]
That is something else entirely, this would be best worked out on monday. Take your branches and revert them back to before the merge, use the local launch so that you can see edits and the like immediately. Get the pages done and looking like they should. Make a local database and use that for now.

**Comment by a-littlefield** [comment]
Will do

**Comment by a-littlefield** [comment]
How do I revert back the master branch? Or should I not worry about it for now? My other branches weren't committed so they should be fine

**Comment by komarnickolas** [comment]
Just leave it for now
